### PR TITLE
Multilib repo

### PR DESCRIPTION
**Pull request by danfossi**
On x86_64 system the multilib repository is automatically enabled.

### CODE REVIEW

**Comment by vitamins** [comment]
Hi danfossi,

multilib is a good idea, but i.m.h.o it is better not to enable it by default.
I have some questions about the code:
1. Why do we enable multilib on the ->install host<- in this line?
sed -i '/#[multilib]/,/#Include = \/etc\/pacman.d\/mirrorlist/ s/#//' /etc/pacman.conf
2. Should the modification happen before the 'pacstrap base' command instead of afterwards? Otherwise the multilib repository is not used for the inital installation of gcc-libs-multilib and other packages.
3. Do you think it is a good idea to add a (yes/no) variable about using multilib ?
   (Adding to many variables makes configuration more complicated, so maybe not.)
4. You can also use echo instead of sed, which simplifies things a bit:
   echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf
   ( I am not capable of understanding sed, so that is why i am not a friend of it.)
   On the other hand using echo will duplicate the multilib entry in pacman.conf .

I am all in favor of merging this after the questions have been discussed.
All the best

**Comment by danfossi** [comment]
Hi mate, 
is not a problem if we don't add multilib but I think that can be useful for additional packages . 

1- I've added it also on install host because if a user want to install skype (as additional packages so with 'pacstrap' ) it needs multilib to work 

2- I do not think that multilib is necessary for the installation of the base system (but I can be wrong!) 

3- Yes, it is a good idea. although next depends on whether or not the user will 
install additional packages or may not require the multilib. A standard user 
might not know if the package they need is in that repository 

4- As you prefer my friend, with sed we prevent the duplication of the entry in the pacman.conf, but echo that's fine too. 

All the best a good week end, 

## 

Dennis Anfossi 
Area Tecnica 

Email: dennis.anfossi@itfor.it 

ITfor s.r.l. 
Corso Svizzera, 185 
10149 Torino (TO) - Italy 
Web: http://www.itfor.it 
Phone: +39.011.7509792 
Fax: +39.011.7778959 

----- Messaggio originale -----

Da: "vitamins" notifications@github.com 
A: "vitamins/archinstaller" archinstaller@noreply.github.com 
Cc: "Dennis" danfossi@itfor.it 
Inviato: Venerdì, 25 ottobre 2013 17:49:38 
Oggetto: Re: [archinstaller] Multilib repo (#12) 

Hi danfossi, 
multilib is a good idea, but i.m.h.o it is better not to enable it by default. 
I have some questions about the code: 
1. Why do we enable multilib on the ->install host<- in this line? 
sed -i '/#[multilib]/,/#Include = \/etc\/pacman.d\/mirrorlist/ s/#//' /etc/pacman.conf 
2. Should the modification happen before the 'pacstrap base' command instead of afterwards? Otherwise the multilib repository is not used for the inital installation of gcc-libs-multilib and other packages. 
3. Do you think it is a good idea to add a (yes/no) variable about using multilib ? 
(Adding to many variables makes configuration more complicated, so maybe not.) 
4. You can also use echo instead of sed, which simplifies things a bit: 
echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /mnt/etc/pacman.conf 
( I am not capable of understanding sed, so that is why i am not a friend of it.) 
On the other hand using echo will duplicate the multilib entry in pacman.conf . 
I am all in favor of merging this after the questions have been discussed. 
All the best

**Comment by vitamins** [comment]
After more thought, i come to the conclusion that it is better not to introduce multitlib. There are often two conflicting versions of packages in the repositories, for example gcc-libs-multilib and gcc-libs. The installation could be interrupted by a question like this:
:: gcc-libs and gcc-libs-multilib are conflicting. Remove gcc-libs ?
This is a problem if you want the script to run automated, and might lead to more problems if a user makes the wrong decision.
It is easier to let users enable multilib after rebooting, when they know what they are doing and why they need it.

**Comment by danfossi** [comment]
Yes, you've right..  it's more simple for the user to remove some characters in pacman.conf rather that managing situations like:

> :: gcc-libs and gcc-libs-multilib are conflicting. Remove gcc-libs ?
> 
> as you said. So, I agree with you that is better not add multilib. In this way we prevent a failure for a bad choice and less variables in ari.conf. :)

## All the best,

Dennis Anfossi 
Area Tecnica 

Email: dennis.anfossi@itfor.it 

ITfor s.r.l. 
Corso Svizzera, 185
10149 Torino (TO) - Italy 
Web: http://www.itfor.it 
Phone: +39.011.7509792 
Fax: +39.011.7778959

Il giorno 25/ott/2013, alle ore 19:38, vitamins notifications@github.com ha scritto:

**Pull request closed without merging**
