### PR TITLE
Update archinstaller_0.4.3.sh

### PR DESCRIPTION
**Pull request by danfossi**
- Added the ability to install Xorg
- Added the ability to install Desktop Environment
  *\* (xfce4/gnome/kde/mate/cinnamon/lxde/enlightenment17)
- Added the ability to install Display Manager
  *\* (gdm/kdebase-workspace/lxdm/xorg-xdm)

### CODE REVIEW

**Comment by vitamins** [comment]
Hi,

the arch linux wiki says it is necessary to install a video driver before installing Xorg. I think there are systems where Xorg refuses to run properly without installing the right video driver.
https://wiki.archlinux.org/index.php/Xorg#Driver_installation

Given the complexity of this issue, i think Xorg should not be included in an automated script.
However i do not mean to discourage you from developing a solution.

All the best

**Comment by danfossi** [comment]
Hi Mate,
doing pacstrap xorg without arguments should install all the drivers, do you think you can, start xorg with the vesa driver and integrate rather specific drivers at a later time? maybe grep lspci ..

Cheers

**Comment by vitamins** [comment]
Yes you are right, this command installs the complete xorg group.
pacstrap /mnt xorg xorg-xinit

I do not think it is a good idea to do it, because you will end up with a lot of unnecessary packages.
For example on my system i have installed 33 packages from the xorg group, and everything runs just fine.
 pacman -Qg xorg | wc -l
 33
Compare this to the amount of packages in the xorg group
pacman -Sg xorg | wc -l
77

You can definitly start xorg with the vesa driver, but desktop environments will run really bad due to the lack of 2D acelleration.

**Comment by danfossi** [comment]
Yes, You've right..
We can just install vesa driver and leave it to the user to install the driver inherent in its video card ? 
Although not the best performance, we can still start the graphics, without burdening the system with useless packets. what do you say? you seem acceptable?

**Comment by vitamins** [comment]
Alright, i think it is acceptable to install the vesa driver, because pacman says it is only 0,04 MiB big.
So the pacstrap command looks like this:
pacstrap /mnt  xorg-server xf86-video-vesa xorg-xinit

Another thing:
Please remove the MATE desktop environment from the list, because it is not officially supported and has to be downloaded from another repository. I think we can again leave it to the user to install unsupported stuff.
https://wiki.archlinux.org/index.php/Desktop_Environment#Officially_supported

Also we should move the section "additional packages" towards the end of the script. Currently when a user configures the packages list like this:
packages='firefox'
,pacman will install xorg as a dependency of firefox. If we move this section after the installation of xorg, this is solved.

Regarding the display manager, you have to take into account, that most display managers need to be enabled.
For example GDM requires this command to run on boot:
"systemctl enable gdm.service"
Please look up how to enable the display managers, and add the code in the section "install display manager" .

**Comment by danfossi** [comment]
Hi mate,
I've modified the script as agreed and added option to select if display_manager need to start on boot or not.

Cheers

**Pull request closed without merging**
